const position = { x: 500, y: 500 };

export const initialNodes = [
  {
    id: "1",
    type: "table",
    data: {
      name: "MT_GENRE",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "2",
    type: "table",
    data: {
      name: "address",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "2a",
    type: "table",
    data: {
      name: "document",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "2b",
    type: "table",
    data: {
      name: "wallet",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "2c",
    type: "table",
    data: {
      name: "devices",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "2d",
    type: "table",
    data: {
      name: "table_2d",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "3",
    type: "table",
    data: {
      name: "table_3",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "4",
    type: "table",
    data: {
      name: "table_4",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "5",
    type: "table",
    data: {
      name: "table_5",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "6",
    type: "table",
    data: {
      name: "table_6",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
    position,
  },
  {
    id: "7",
    type: "table",
    data: {
      name: "table_7",
      columns: [
        {
          fieldName: "GENDER_CD",
          valueType: "SEQUENTIALLY",
          dataType: "NUMBERIC",
          value: "28:999",
          length: 4,
        },
        {
          fieldName: "GENDER_NM",
          valueType: "RANDOM",
          dataType: "FULL_NAME",
          value: "",
          length: 80,
        },
        {
          fieldName: "INDUSTRY_CD",
          valueType: "RANDOM",
          dataType: "CODE",
          value: "02,03",
          length: 2,
        },
        {
          fieldName: "USE_STP_F",
          valueType: "FIXED",
          dataType: "NUMBERIC",
          value: "3:99",
          length: 2,
        },
      ],
    },
  },
];

export const initialEdges = [
  { id: "e12", source: "1", target: "2", type: "smoothstep" },
  { id: "e13", source: "1", target: "3", type: "smoothstep" },
  { id: "e22a", source: "2", target: "2a", type: "smoothstep" },
  { id: "e22b", source: "2", target: "2b", type: "smoothstep" },
  { id: "e22c", source: "2", target: "2c", type: "smoothstep" },
  { id: "e2c2d", source: "2c", target: "2d", type: "smoothstep" },
  { id: "e45", source: "4", target: "5", type: "smoothstep" },
  { id: "e56", source: "5", target: "6", type: "smoothstep" },
  { id: "e57", source: "5", target: "7", type: "smoothstep" },
];
